apiVersion: v1
kind: Service
metadata:
  labels:
    name: sentinel
    role: service
  name: redis-sentinel
spec:
  type: LoadBalancer 
  ports:
    - port: 8089
      targetPort: 6379
  selector:
    redis-sentinel: "true"
