apiVersion: v1
kind: ConfigMap
metadata:
  name: csye7374-app-config
data:
  redis_service_name: redis-master-service

---
apiVersion: v1               
kind: ReplicationController                    
metadata:
  name: csye7374-app-rc        
spec:
  replicas: 3
  selector:
    app: csye7374-app
  template:
    metadata:
      labels:
        app: csye7374-app
    spec:
      containers:
      - image: fangn/csye7374:pw     
        name: csye7374-app-container
        env:
        - name: SERVICE_NAME                
          valueFrom:                     
            configMapKeyRef:             
              name: csye7374-app-config     
              key: redis_service_name

        - name: REDIS_PASSWD                
          valueFrom:                     
            secretKeyRef:             
              name: redis-secret     
              key: config
        # imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 5
        ports:
        - containerPort: 8082    
          protocol: TCP
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
          requests:
            memory: "32Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: csye7374-app-svc
spec:
  type: LoadBalancer             
  ports:
  - port: 80                 
    targetPort: 8082                  
  selector:
    app: csye7374-app
